import { Sacco } from "./types";

export const saccos: Sacco[] = [
  {
    id: 1,
    name: "Mwalimu National SACCO",
    focus: "Education & Agriculture Focus",
    rate: 12,
    maxLoan: 500000,
    repayment: "harvest-aligned",
    harvestMonths: ["Mar", "Jun", "Oct"],
    countyFocus: "National",
    badge: "Best for Farmers",
    contact: {
      phone: "+254 20 221 7000",
      whatsapp: "254722170000",
      website: "https://mwalimusacco.com",
      branches: [
        "Nairobi CBD — Anniversary Towers, 2nd Floor",
        "Mombasa — Nkrumah Road, TSS Building",
        "Kisumu — Oginga Odinga St, Mega Plaza",
        "Nakuru — Kenyatta Avenue, Gilani Building",
      ],
      documents: [
        "National ID (original + copy)",
        "Recent farm produce/sales records (3 months)",
        "School fee structure / invoice",
        "2 passport photos",
        "KRA PIN certificate",
      ],
    },
  },
  {
    id: 2,
    name: "Stima SACCO",
    focus: "Energy & Enterprise Focus",
    rate: 13.5,
    maxLoan: 300000,
    repayment: "flexible",
    harvestMonths: ["any"],
    countyFocus: "National",
    badge: "Flexible Terms",
    contact: {
      phone: "+254 20 247 3000",
      whatsapp: "254733470000",
      website: "https://stimasacco.com",
      branches: [
        "Nairobi — Stima Plaza, Kolobot Road",
        "Mombasa — Shimanzi Road, Light House",
        "Kisumu — Ang'awa Avenue",
      ],
      documents: [
        "National ID (original + copy)",
        "Latest 3 months bank statement",
        "School fee structure / invoice",
        "2 passport photos",
        "KRA PIN certificate",
        "Business permit (for traders)",
      ],
    },
  },
  {
    id: 3,
    name: "Kenya Police SACCO",
    focus: "Formal Employment Focus",
    rate: 10,
    maxLoan: 800000,
    repayment: "monthly",
    harvestMonths: ["any"],
    countyFocus: "National",
    badge: "Lowest Rate",
    contact: {
      phone: "+254 20 222 2000",
      whatsapp: "254722220000",
      website: "https://kenyapoliceSacco.co.ke",
      branches: [
        "Nairobi — Upper Hill, KP SACCO House",
        "Mombasa — Mama Ngina Drive",
        "Eldoret — Uganda Road",
        "Nyeri — Kimathi Way",
      ],
      documents: [
        "National ID (original + copy)",
        "Last 3 months payslips",
        "Employment confirmation letter",
        "School fee structure / invoice",
        "2 passport photos",
        "KRA PIN certificate",
      ],
    },
  },
  {
    id: 4,
    name: "Afya SACCO",
    focus: "Health & Community Focus",
    rate: 11,
    maxLoan: 200000,
    repayment: "harvest-aligned",
    harvestMonths: ["Apr", "Sept"],
    countyFocus: "National",
    badge: "Community Focus",
    contact: {
      phone: "+254 722 411 411",
      whatsapp: "254722411411",
      website: "https://afyasacco.co.ke",
      branches: [
        "Nairobi — Afya Centre, Tom Mboya St",
        "Kisumu — Kondele Market, Bondo Rd",
        "Meru — Meru Town, Stadium Rd",
      ],
      documents: [
        "National ID (original + copy)",
        "Recent income evidence (3 months)",
        "School fee structure / invoice",
        "2 passport photos",
        "Community leader recommendation letter",
      ],
    },
  },
  {
    id: 5,
    name: "Ukulima SACCO",
    focus: "Agriculture Focus",
    rate: 9.5,
    maxLoan: 400000,
    repayment: "harvest-aligned",
    harvestMonths: ["Mar", "Apr", "Sept", "Oct"],
    countyFocus: "National",
    badge: "Best for Farmers",
    contact: {
      phone: "+254 20 222 5000",
      whatsapp: "254722250000",
      website: "https://ukulimasacco.co.ke",
      branches: [
        "Nairobi — Uchumi House, Aga Khan Walk",
        "Nakuru — Kenyatta Avenue",
        "Thika — Commercial Street",
        "Nyeri — Kimathi Way",
        "Eldoret — Uganda Road",
      ],
      documents: [
        "National ID (original + copy)",
        "Farm registration / ownership documents",
        "Last season produce / delivery receipts",
        "School fee structure / invoice",
        "2 passport photos",
        "KRA PIN certificate",
      ],
    },
  },
  {
    id: 6,
    name: "Imarika SACCO",
    focus: "Micro & Small Enterprise Focus",
    rate: 14,
    maxLoan: 150000,
    repayment: "flexible",
    harvestMonths: ["any"],
    countyFocus: "National",
    badge: "Best for Vendors",
    contact: {
      phone: "+254 722 788 000",
      whatsapp: "254722788000",
      website: "https://imarikasacco.co.ke",
      branches: [
        "Kilifi — Imarika SACCO Plaza",
        "Mombasa — Digo Road",
        "Malindi — Lamu Road",
      ],
      documents: [
        "National ID (original + copy)",
        "Business permit",
        "Last 3 months M-Pesa statement",
        "School fee structure / invoice",
        "2 passport photos",
      ],
    },
  },
  {
    id: 7,
    name: "Safaricom SACCO",
    focus: "Technology & Commerce Focus",
    rate: 11.5,
    maxLoan: 350000,
    repayment: "monthly",
    harvestMonths: ["any"],
    countyFocus: "National",
    badge: "Fast Approval",
    contact: {
      phone: "+254 722 004 000",
      whatsapp: "254722004000",
      website: "https://safarisacco.co.ke",
      branches: [
        "Nairobi — Safaricom House, Waiyaki Way",
        "Mombasa — Safaricom House, Nyali",
        "Kisumu — Safaricom Office, Oginga Odinga",
      ],
      documents: [
        "National ID (original + copy)",
        "Latest 3 months payslips or business records",
        "School fee structure / invoice",
        "2 passport photos",
        "KRA PIN certificate",
      ],
    },
  },
];
